apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace/namespace.yaml
  - minio
  - kubescape
  - popeye
  - kubevious
  - normalizer
  - rbac
  - networkpolicy
  - holmesgpt
