apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headscale
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/agud97/idp-app-v1.git
    path: platform/headscale
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: headscale
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
