# HolmesGPT - ArgoCD Application
# Версия 0.19.0 + prometheus/metrics toolset для VictoriaMetrics

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: holmesgpt
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://robusta-charts.storage.googleapis.com
    chart: holmes
    targetRevision: "0.19.0"
    helm:
      values: |
        # LLM конфигурация
        additionalEnvVars:
          - name: MODEL
            value: "openai/qwen"
          - name: OPENAI_API_BASE
            value: "http://89.104.65.97:30507/openai/v1"
          - name: OPENAI_API_KEY
            value: "sk-eeghuh2cein1ziech8jaiM0ohcaim8qu"

        # Toolsets
        toolsets:
          kubernetes/core:
            enabled: true
          kubernetes/logs:
            enabled: true
          prometheus/metrics:
            enabled: true
            config:
              prometheus_url: "http://vmsingle-vm-k8s-stack-victoria-metrics-k8s-stack.monitoring.svc:8429"
          runbook:
            enabled: true
          bash:
            enabled: true
            config:
              include_default_allow_deny_list: true

        # Custom runbooks via additionalVolumes (supported in 0.19.0)
        additionalVolumes:
          - name: custom-runbooks
            configMap:
              name: custom-runbooks
          - name: sre-runbooks
            configMap:
              name: sre-runbooks
        additionalVolumeMounts:
          - name: custom-runbooks
            mountPath: /app/holmes/plugins/runbooks/custom-runbooks.yaml
            subPath: custom-runbooks.yaml
          - name: sre-runbooks
            mountPath: /app/holmes/plugins/runbooks/sre-runbooks.yaml
            subPath: sre-runbooks.yaml

        # Resources
        resources:
          requests:
            memory: "2048Mi"
            cpu: "500m"
          limits:
            memory: "4096Mi"
            cpu: "2000m"

  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/spec/volumes
        - /spec/template/spec/containers/0/volumeMounts
  destination:
    server: https://kubernetes.default.svc
    namespace: holmesgpt
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
