apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openldap
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://jp-gouin.github.io/helm-openldap/
    chart: openldap
    targetRevision: "2.0.4"
    helm:
      values: |
        replicaCount: 1
        env:
          LDAP_DOMAIN: "runityai.local"
          LDAP_ORGANISATION: "RunityAI"
          LDAP_TLS: "false"
          LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
        adminPassword: "LdapAdmin1234"
        configPassword: "LdapConfig1234"
        replication:
          enabled: false
        ltb-passwd:
          enabled: false
        phpldapadmin:
          enabled: false
        persistence:
          enabled: true
          size: 1Gi
          storageClass: openebs-hostpath
        customLdifFiles:
          01-users-groups.ldif: |
            dn: ou=people,dc=runityai,dc=local
            objectClass: organizationalUnit
            ou: people

            dn: ou=groups,dc=runityai,dc=local
            objectClass: organizationalUnit
            ou: groups

            dn: uid=admin1,ou=people,dc=runityai,dc=local
            objectClass: inetOrgPerson
            objectClass: posixAccount
            objectClass: shadowAccount
            uid: admin1
            cn: admin1
            sn: admin1
            uidNumber: 1001
            gidNumber: 1001
            homeDirectory: /home/admin1
            userPassword: {CLEARTEXT}Admin1Pass!
            mail: admin1@runityai.local

            dn: uid=user1,ou=people,dc=runityai,dc=local
            objectClass: inetOrgPerson
            objectClass: posixAccount
            objectClass: shadowAccount
            uid: user1
            cn: user1
            sn: user1
            uidNumber: 1002
            gidNumber: 1002
            homeDirectory: /home/user1
            userPassword: {CLEARTEXT}User1Pass!
            mail: user1@runityai.local

            dn: cn=prod_runityai_admin,ou=groups,dc=runityai,dc=local
            objectClass: posixGroup
            objectClass: uidObject
            cn: prod_runityai_admin
            uid: prod_runityai_admin
            gidNumber: 2000
            memberUid: admin1

            dn: cn=prod_runityai_user,ou=groups,dc=runityai,dc=local
            objectClass: posixGroup
            objectClass: uidObject
            cn: prod_runityai_user
            uid: prod_runityai_user
            gidNumber: 2001
            memberUid: user1
  destination:
    server: https://kubernetes.default.svc
    namespace: openldap
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
