apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://openebs.github.io/dynamic-localpv-provisioner
    chart: localpv-provisioner
    targetRevision: "4.1.0"
    helm:
      values: |
        hostpathClass:
          enabled: true
          isDefaultClass: true
          name: openebs-hostpath
          basePath: /var/openebs/local
        deviceClass:
          enabled: false
        localpv:
          image:
            registry: docker.io/
            repository: openebs/provisioner-localpv
            tag: 4.1.0
        helperPod:
          image:
            registry: docker.io/
            repository: openebs/linux-utils
            tag: 4.1.0
  destination:
    server: https://kubernetes.default.svc
    namespace: openebs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
