apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qdrant
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://qdrant.github.io/qdrant-helm
    chart: qdrant
    targetRevision: "0.10.1"
    helm:
      values: |
        replicaCount: 1
        persistence:
          size: 5Gi
          storageClassName: openebs-hostpath
        service:
          type: ClusterIP
          ports:
            - name: rest
              port: 6333
              targetPort: 6333
              protocol: TCP
            - name: grpc
              port: 6334
              targetPort: 6334
              protocol: TCP
  destination:
    server: https://kubernetes.default.svc
    namespace: qdrant
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
