# VictoriaLogs - ArgoCD Application

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-logs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://victoriametrics.github.io/helm-charts
    chart: victoria-logs-single
    targetRevision: "0.11.26"
    helm:
      values: |
        server:
          retentionPeriod: 30d
          persistentVolume:
            enabled: true
            storageClass: openebs-hostpath
            size: 50Gi
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 1Gi

  destination:
    server: https://kubernetes.default.svc
    namespace: victorialogs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
