# VictoriaLogs Collector - ArgoCD Application

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-logs-collector
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://victoriametrics.github.io/helm-charts
    chart: victoria-logs-collector
    targetRevision: "0.16.0"
    helm:
      values: |
        remoteWrite:
          - url: "http://vls-victoria-logs-single-server.victorialogs.svc:9428"

  destination:
    server: https://kubernetes.default.svc
    namespace: victorialogs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
