apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: kubevious
    repo: https://helm.kubevious.io
    version: 1.0.79
    releaseName: kubevious
    namespace: kb-system
    valuesInline:
      ui:
        service:
          type: ClusterIP
      backend:
        readOnly: true
resources:
  - kubevious-exporter-cronjob.yaml
