apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: kubevious
    repo: https://helm.kubevious.io
    version: 1.2.2
    releaseName: kubevious
    namespace: kb-system
    valuesInline:
      ui:
        service:
          type: ClusterIP
      backend:
        readOnly: true
        livenessProbe:
          initialDelaySeconds: 30
          timeoutSeconds: 2
          periodSeconds: 10
          failureThreshold: 6
        readinessProbe:
          initialDelaySeconds: 10
          timeoutSeconds: 2
          periodSeconds: 10
          failureThreshold: 6
resources:
  - kubevious-exporter-cronjob.yaml
