apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xmessagingapps.idp.example.com
spec:
  group: idp.example.com
  names:
    kind: XMessagingApp
    plural: xmessagingapps
  claimNames:
    kind: MessagingApp
    plural: messagingapps
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                environmentName:
                  type: string
                  description: "Environment name prefix (optional)"
                services:
                  type: array
                  description: "List of services: broker, producer, consumer"
                  items:
                    type: object
                    required:
                      - name
                      - image
                    properties:
                      name:
                        type: string
                      image:
                        type: string
                      replicas:
                        type: integer
                        default: 1
                      port:
                        type: integer
                        default: 80
                      env:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            value:
                              type: string
                          required:
                            - name
                            - value
                      secrets:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            value:
                              type: string
                          required:
                            - name
                            - value
                      ingress:
                        type: object
                        properties:
                          enabled:
                            type: boolean
                            default: false
                          host:
                            type: string
                          path:
                            type: string
                            default: "/"
            status:
              type: object
              properties:
                ready:
                  type: boolean
                serviceCount:
                  type: integer
