# Example Application with Database for IDP
# Developers: copy this file and modify for your application
apiVersion: idp.example.com/v1alpha1
kind: ApplicationWithDB
metadata:
  name: backend-api
  namespace: default
spec:
  # Required: Application name
  name: backend-api

  # Required: Docker image
  image: nginx:latest  # Replace with your app image

  # Optional: Number of replicas (default: 1)
  replicas: 2

  # Optional: Container port (default: 80)
  port: 8080

  # Optional: Environment variables (stored in ConfigMap)
  env:
    - name: APP_ENV
      value: production
    - name: LOG_LEVEL
      value: info

  # Optional: Secret environment variables (stored in Secret)
  secrets:
    - name: JWT_SECRET
      value: my-jwt-secret-key

  # Database configuration
  database:
    enabled: true
    engine: postgres
    version: "15"
    storage: "1Gi"
    dbName: backend_db      # Database name
    username: backend_user  # Database username
    password: secretpass123 # Database password
    # Connection string will be available as DATABASE_URL env var

  # Migration configuration (runs as init container before app starts)
  migration:
    enabled: true
    image: nginx:latest  # Replace with your migration image
    command:
      - "/bin/sh"
      - "-c"
      - "echo 'Running migrations...' && sleep 5 && echo 'Migrations complete!'"
    # Real example:
    # image: myapp:latest
    # command:
    #   - "/app/migrate"
    #   - "up"

  # Optional: Ingress configuration
  ingress:
    enabled: true
    host: backend-api.example.com
