apiVersion: idp.example.com/v1alpha1
kind: TestEnvironment
metadata:
  name: qa-check-env
  namespace: default
  labels:
    app.kubernetes.io/managed-by: backstage
    environment: qa-check
spec:
  name: qa-check

  frontend:
    enabled: true
    replicas: 1

  backend:
    enabled: false
    

  platform:
    enabled: false

  staticFiles:
    enabled: false

  docs:
    enabled: false
