# Test: Application with Database and Migration
apiVersion: idp.example.com/v1alpha1
kind: ApplicationWithDB
metadata:
  name: test-app-with-db
  namespace: default
spec:
  name: test-app-with-db
  image: nginx:alpine
  replicas: 2
  port: 8080

  env:
    - name: APP_NAME
      value: test-app-with-db
    - name: ENVIRONMENT
      value: testing

  database:
    enabled: true
    engine: postgres
    version: "15"
    storage: "1Gi"
    dbName: testdb
    username: testuser
    password: testpass123

  migration:
    enabled: true
    image: postgres:15
    command:
      - "/bin/sh"
      - "-c"
      - |
        echo "=== Starting migration ==="
        echo "Waiting for database..."
        until pg_isready -h test-app-with-db-db -p 5432 -U testuser; do
          sleep 2
        done
        echo "Database is ready!"
        PGPASSWORD=$POSTGRES_PASSWORD psql -h test-app-with-db-db -U testuser -d testdb -c "CREATE TABLE IF NOT EXISTS migrations (id SERIAL PRIMARY KEY, name VARCHAR(255), applied_at TIMESTAMP DEFAULT NOW());"
        PGPASSWORD=$POSTGRES_PASSWORD psql -h test-app-with-db-db -U testuser -d testdb -c "INSERT INTO migrations (name) VALUES ('initial_migration');"
        echo "=== Migration completed ==="

  ingress:
    enabled: true
    host: test-app-with-db.example.com
