apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - alertmanager-webhook.yaml
  - custom-runbooks-configmap.yaml
  - kb-stack-toolset.yaml
  - knowledge-base-toolset.yaml
  - sre-runbooks.yaml
  - victorialogs-toolset.yaml
  - vmalertmanagerconfig.yaml
