apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vlogs-cold-storage
  namespace: victorialogs
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: openebs-hostpath-cold
  resources:
    requests:
      storage: 50Gi
